[build]
  publish = "public"

[[redirects]]
  from = "/api/products"
  to = "https://api.muebleslottus.com/api/paginaweb/products/"
  status = 200
  force = true

[[redirects]]
  from = "/api/products/*"
  to = "https://api.muebleslottus.com/api/paginaweb/products/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/settings"
  to = "https://api.muebleslottus.com/api/paginaweb/settings/"
  status = 200
  force = true

[[redirects]]
  from = "/api/asesores"
  to = "https://api.muebleslottus.com/api/paginaweb/asesores/"
  status = 200
  force = true

[[redirects]]
  from = "/api/asesores/*"
  to = "https://api.muebleslottus.com/api/paginaweb/asesores/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "https://api.muebleslottus.com/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/media/*"
  to = "https://api.muebleslottus.com/media/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/catalogo"
  to = "/catalogo.html"
  status = 200

[[redirects]]
  from = "/sora"
  to = "/sora.html"
  status = 200

[[redirects]]
  from = "/contacto"
  to = "/contacto.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/producto/:slug"
  to = "/producto.html"
  status = 200

[[redirects]]
  from = "/asesor/:slug"
  to = "/asesor.html"
  status = 200
